apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: k8s-microservices
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
  POSTGRES_DB: microservices_db

