apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-binding
  namespace: k8s-microservices
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: api-gateway-sa
  namespace: k8s-microservices
roleRef:
  kind: Role
  name: api-gateway-role
  apiGroup: rbac.authorization.k8s.io

