apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-binding
  namespace: k8s-microservices
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: frontend-sa
  namespace: k8s-microservices
roleRef:
  kind: Role
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io

