apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-service-binding
  namespace: k8s-microservices
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: product-service-sa
  namespace: k8s-microservices
roleRef:
  kind: Role
  name: product-service-role
  apiGroup: rbac.authorization.k8s.io

